# Generated by Django 4.0.5 on 2022-06-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pfoto',
            new_name='photo',
        ),
    ]
